"""Extract frozen DINOv3 features for project images.

Pipeline role:
- reads image manifests such as ``data/processed/train/*_train.csv`` or the
  master image manifest generated by the Makefile;
- loads a frozen DINOv3 backbone and converts each image into an embedding;
- writes image-level and asset-level feature CSVs under ``data/features``.

Those asset-level feature CSVs are consumed by
``scripts/run_dinov3_classifier.py`` for cross-validation experiments and by
``scripts/train_final_classifiers.py`` for the saved final inference bundle.

Single attribute:
    python scripts/extract_dinov3_features.py \
        --input data/processed/train/attr_decking_material_train.csv \
        --output data/features/dinov3_vitb16_attr_decking_material_images.csv \
        --asset-output data/features/dinov3_vitb16_attr_decking_material_assets.csv \
        --model dinov3_vitb16

All attributes in a directory:
    python scripts/extract_dinov3_features.py \
        --input-dir data/processed/train \
        --output-dir data/features \
        --model dinov3_vitb16

If the machine cannot download from torch.hub, clone the official DINOv3 repo
elsewhere and pass ``--model-source /path/to/dinov3``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.dinov3_features import (  # noqa: E402
    DEFAULT_DINOV3_MODEL,
    DEFAULT_IMAGE_ROOT,
    aggregate_asset_features,
    extract_image_features,
)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for this script."""
    parser = argparse.ArgumentParser(
        description="Extract DINOv3 image embeddings and aggregate them by asset_id."
    )
    # --- input: one of --input or --input-dir ---
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument("--input", type=Path, help="Single CSV with asset_id and image_path columns.")
    input_group.add_argument("--input-dir", type=Path, help="Directory of attr_*.csv files to process in bulk.")

    # --- output: per-file flags (single mode) or a directory (bulk mode) ---
    parser.add_argument("--output", type=Path, default=None, help="Image-level feature CSV (single mode).")
    parser.add_argument("--asset-output", type=Path, default=None, help="Asset-level averaged feature CSV (single mode).")
    parser.add_argument("--output-dir", type=Path, default=None, help="Output directory for bulk mode.")
    parser.add_argument("--skipped-output", type=Path, default=None, help="Optional CSV for missing/unreadable images (single mode).")

    parser.add_argument("--image-root", type=Path, default=DEFAULT_IMAGE_ROOT)
    parser.add_argument("--model", default=DEFAULT_DINOV3_MODEL)
    parser.add_argument("--model-source", default="facebookresearch/dinov3")
    parser.add_argument(
        "--weights",
        default=None,
        help="DINOv3 checkpoint URL or local .pth path from approved model-weight access.",
    )
    parser.add_argument("--device", default=None, help="cuda, cpu, mps, or omitted for auto.")
    parser.add_argument("--image-size", type=int, default=224)
    parser.add_argument("--limit-assets", type=int, default=None, help="Optional smoke-test limit.")
    return parser.parse_args()


def get_output_paths(input_path: Path, output_dir: Path) -> tuple[Path, Path, Path]:
    """Derive image, asset, and skipped output paths from an input CSV filename."""
    stem = input_path.stem  # e.g. attr_decking_material_train
    return (
        output_dir / f"dinov3_{stem}_images.csv",
        output_dir / f"dinov3_{stem}_assets.csv",
        output_dir / f"dinov3_{stem}_skipped.csv",
    )

def process_one(
    input_path: Path,
    output_path: Path,
    asset_output_path: Path,
    skipped_output_path: Path,
    args: argparse.Namespace,
) -> None:
    """Extract features for one input CSV and write image and asset feature outputs."""
    print(f"\n{'='*60}")
    print(f"Processing: {input_path.name}")
    print(f"{'='*60}")

    rows = pd.read_csv(input_path)
    if args.limit_assets is not None:
        keep_assets = rows["asset_id"].drop_duplicates().head(args.limit_assets)
        rows = rows[rows["asset_id"].isin(keep_assets)]

    features, skipped = extract_image_features(
        rows,
        image_root=args.image_root,
        model_name=args.model,
        model_source=args.model_source,
        weights=args.weights,
        device=args.device,
        image_size=args.image_size,
        repo_root=REPO_ROOT,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    asset_output_path.parent.mkdir(parents=True, exist_ok=True)
    features.to_csv(output_path, index=False)

    if features.empty:
        print("No image features extracted. Check --image-root and image availability.")
    else:
        asset_features = aggregate_asset_features(features)
        asset_features.to_csv(asset_output_path, index=False)
        print(f"  Wrote {len(features)} image rows  → {output_path}")
        print(f"  Wrote {len(asset_features)} asset rows → {asset_output_path}")

    if not skipped.empty:
        skipped_output_path.parent.mkdir(parents=True, exist_ok=True)
        skipped.to_csv(skipped_output_path, index=False)
        print(f"  Wrote {len(skipped)} skipped rows → {skipped_output_path}")


def main() -> int:
    """Run the script from parsed command-line arguments."""
    args = parse_args()

    if args.input_dir:
        # --- bulk mode ---
        if args.output_dir is None:
            print("Error: --output-dir is required when using --input-dir.")
            return 1

        csv_files = sorted(args.input_dir.glob("attr_*.csv"))
        if not csv_files:
            print(f"No attr_*.csv files found in {args.input_dir}")
            return 1

        print(f"Found {len(csv_files)} attribute CSV(s) in {args.input_dir}")
        for csv_path in csv_files:
            img_out, asset_out, skipped_out = get_output_paths(csv_path, args.output_dir)
            process_one(csv_path, img_out, asset_out, skipped_out, args)

        print(f"\nDone. Processed {len(csv_files)} attribute file(s).")

    else:
        # --- single attribute mode ---
        if args.output is None or args.asset_output is None:
            print("Error: --output and --asset-output are required when using --input.")
            return 1

        skipped_path = args.skipped_output or args.output.with_name(f"{args.output.stem}_skipped.csv")
        process_one(args.input, args.output, args.asset_output, skipped_path, args)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
